default: &default
  host: localhost
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: scout-hike-development
  username: carsoncole
  password: password

test:
  <<: *default
  database: scout-hike-test
  username: carsoncole
  password: password
